--- SELECT BASIC // TODAS INFORMAÇÕES
SELECT * FROM AGENDA;

--- SELECT COM DETERMINADAS COLUNAS
SELECT NOMEAGENDA FROM AGENDA;


--- EXPRESSÕES ARITMÉTICAS
SELECT NOMEAGENDA, DIAMES * 2 FROM AGENDA;
SELECT NOMEAGENDA, DIAMES * 2 + 100 FROM AGENDA;

SELECT NOMEAGENDA, DIAMES + 100 * 2 FROM AGENDA; -- PRIMEIRO A MULTIPLICAÇÃO
SELECT NOMEAGENDA, (DIAMES + 100) * 2 FROM AGENDA; -- PRIMEIRO O PARÊNTESE

--- VALOR NULL
--- NULL É A AUSÊNCIA DE VALOR
--- LOCALIZAR VALOR POR IS NULL


--- ALIAS DE COLUNA || RENAME PARA O NOME DA COLUNA DURANTE O SELECT
SELECT NOMEAGENDA AS nome FROM AGENDA;
SELECT NOMEAGENDA AS "nome" FROM AGENDA;

--- CONCATENANDO ||
SELECT NOMEAGENDA || ' - Dia: ' || DIAMES AS "Nome e Dia" FROM AGENDA;

------ OPERADOR ALTERNATIVO PARA ASPAS
SELECT NOMEAGENDA || q'[ XX Dia: 'DIAMES']' AS "Nome e Dia" FROM AGENDA;

