--- ORDENAÇÃO
----- ORDER BY
--------- ASC ASCENDENTE
--------- DESC DECRECENTE

SELECT * FROM pcprodut ORDER BY DESCRICAO;
SELECT * FROM pcprodut ORDER BY DESCRICAO ASC;

SELECT * FROM pcprodut ORDER BY DESCRICAO DESC;

