--- BUSCA FILTRADA

SELECT NOMEAGENDA FROM AGENDA WHERE DIAMES = 1;

SELECT * FROM PCCLIENT WHERE BAIRROCOB = 'ELDORADO';

--- OPERADORES DE COMPARAÇÃO
--- = IGUAL A
--- > MAIOR QUE
--- >= MAIOR OU IGUAL A
--- < MENOR QUE
--- <= MENOR OU IGUAL A
--- <> NÃO É IGUAL
--- BETWEEN ...AND... ENTRE DOIS VALORES | INTERVALOS
--- IN(set) LISTA DE VALORES
--- LIKE tipo/igual
--- IS NULL se o valor é nulo

SELECT ALIQUOTA, NUMTRANSVENDA FROM pcnfbase WHERE VLBASE >= 50;

SELECT ALIQUOTA FROM pcnfbase WHERE VLBASE BETWEEN 30 AND 50;

SELECT * FROM pcprodut WHERE CODPROD IN (223, 156, 7744);

SELECT * FROM pcprodut WHERE DESCRICAO LIKE '%LUVA%'; 
    --- TIVE O CARACTERE LUVA ENTRE A STRING
SELECT * FROM pcprodut WHERE DESCRICAO LIKE 'LUVA%'; 
    --- INICIAR COM O CARACTER LUVA SEGUIDA DE QUALQUER COISA O STRING
SELECT * FROM pcprodut WHERE DESCRICAO LIKE '%P'; 
    --- TEMRINA COM O CARACTER P - QUALQUER COISA ANTES

SELECT * FROM pcprodut WHERE DESCRICAO LIKE '_U%';
    --- PRIMEIRO CARACTERER QUALQUER _
    --- SEGUNDO CARACTERER PRECISA SER 'U'
    --- QUALQUER COISA A FRENTE %

--- BUSCA NULL
--- SELECT * FROM EMPLOYEES WHERE MANAGER_ID = NULL; -- RETORNO VAZIO
--- SELECT * FROM EMPLOYEES WHERE MANAGER_ID IS NULL; -- EXIBE OS NULL

--- OPERADORES LÓGICOS
--- AND -> RETORNA TRUE QUANDO AMBAS CONDIÇÕES SÃO VERDADEIRAS
--- OR -> RETORNA TRUE QUANDO PELO MENOS UMA DAS CONDIÇÕES FOR VERDADEIRA
--- NOT -> NEGAÇÃO DA CONDIÇÃO
    ---------- SE FOR TRUE RETORNA falsa
    ---------- SE FOR FALSE RETORNA verdadeira
    ---------- SE FOR NULL continua NULL

------ AND
SELECT * FROM pcprodut
    WHERE EMBALAGEM = 'PC'
        AND DESCRICAO LIKE '%T%'; 
        
------ OR
SELECT * FROM pcprodut
    WHERE EMBALAGEM = 'PC'
        OR DESCRICAO LIKE '%TINTA%';
        
------ NOT
SELECT * FROM pcprodut WHERE CODPROD NOT IN (223, 156, 7744);
    --- TUDO MENOS OS CODS 223, 156, 7744

--- REGRAS DE PRECEDÊNCIA
----- OPERADORES ARITMÉTICOS [ESQ -> DIREITA]
----- OPERADORES DE CONCATENAÇÃO
----- OPERADORES DE COMPARAÇÃO
----- IS[NOT] NULL, LIKE, [NOT] IN
----- [NOT] BETWEEN
----- NOT EQUAL TO
----- NOT
----- AND
----- OR
---------- PARÊNTESES TEM PREFERÊNCIA NA ORDEM

--- ENTRADA DE PARAMETRO/variavel
SELECT * FROM pcprodut WHERE CODPROD = &CODPROD; --- N FUNFA AQUI
    ---- caso for &&CODPROD - && pega a variavel anterior
    ---- caso string deve ficar dentro das aspas simples



